title: PDX Fiber
email: media@pdxfiber.com
organizers_email: organizers@pdxfiber.com
description: >
  The advocacy group for municipal broadband in the Portland area.
url: "https://www.pdxfiber.com"
twitter:
  username: PDXFiber
social:
  links:
    - https://twitter.com/PDXFiber
    - https://github.com/pdxfiber
github_username: pdxfiber
jquery_version: 3.2.1
chat_url: "https://kiwiirc.com/client/irc.freenode.net:+6697/pdxfiber"
github_url: "https://github.com/pdxfiber/pdxfiber.com"
google_analytics_tracking_id: UA-111606567-1
mailchimp_subscribe_url: "https://pdxfiber.us17.list-manage.com/subscribe/post?u=671813dc72874a7223ceead45&id=3492e6621c"
meetup_api_url: "https://api.meetup.com/PDX-Fiber/events"
meetup_api_sig_id: 244265326
meetup_api_sig: cc2365295b29a0d8b999ba9f0e6080505845ec13

baseurl: ''
permalink: /blog/:year/:month/:title:output_ext

markdown: kramdown

paginate: 10
paginate_path: /blog/p:num/

timezone: America/Los_Angeles

exclude:
- CODE_OF_CONDUCT.md
- CNAME
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- vendor

plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap

webrick:
  headers:
    Content-Security-Policy: >-
      default-src 'none';
      child-src https:;
      img-src 'self' https://www.google-analytics.com data:;
      font-src 'self';
      script-src 'self' 'sha256-yjeP9f+DRCLMxpxgxQJ3+//xRlOg6r3zbgfv56LlHAE=' https://www.googletagmanager.com https://www.google-analytics.com https://api.meetup.com;
      style-src 'self';
      object-src 'none';
      frame-src https:;
      frame-ancestors 'none'
    X-Content-Type-Options: nosniff
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    Referrer-Policy: strict-origin-when-cross-origin
