title: PDX Fiber
email: media@pdxfiber.com
organizers_email: organizers@pdxfiber.com
description: >
  The advocacy group for municipal broadband in the Portland area.
url: "https://www.pdxfiber.com"
twitter_username: PDX_Fiber
github_username: pdxfiber
jquery_version: 3.2.1
chat_url: "https://kiwiirc.com/client/irc.freenode.net:+6697/pdxfiber"
github_url: "https://github.com/pdxfiber/pdxfiber.com"
google_analytics_tracking_id: UA-111606567-1
mailchimp_subscribe_url: "https://pdxfiber.us17.list-manage.com/subscribe/post?u=671813dc72874a7223ceead45&id=3492e6621c"
meetup_api_url: "https://api.meetup.com/PDX-Fiber/events"
meetup_api_sig_id: 244265326
meetup_api_sig: cc2365295b29a0d8b999ba9f0e6080505845ec13

baseurl: ''

markdown: kramdown

exclude:
- CNAME
- Gemfile
- Gemfile.lock
- vendor

plugins:
- jekyll-sitemap
